spring:
  datasource:
    url: jdbc:h2:mem:telemetrydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: telemetry-ingestion

logging:
  level:
    root: INFO
    com.emf.ingestion: DEBUG
  pattern:
    console: '{"time":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c{1}","message":"%m"}%n'

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: telemetry-ingestion

