spring:
  application:
    name: telemetry-ingestion
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/telemetry}
    username: ${DB_USERNAME:telemetry}
    password: ${DB_PASSWORD:telemetry}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: info